use super::super::style::{Color, DecorationKind};
use super::{Anchor, Backend, Decoration, Label, PathStyle, Segment, Stroke, Theme, Vec2D};

use std::f64;
use std::fmt::Write;

pub struct SVGBackend {
    buf: String,
}

impl SVGBackend {
    fn fmt_color(color: &Color) -> String {
        format!(r##"#{:02x}{:02x}{:02x}"##, color.r, color.g, color.b)
    }

    fn style(&mut self, style: &PathStyle) {
        if style.close {
            self.buf.push_str(" Z");
        }
        write!(
            self.buf,
            r##"" stroke-width="{:.4}" stroke="#{:02x}{:02x}{:02x}""##,
            style.width * Self::BASE_SIZE,
            style.color.r,
            style.color.g,
            style.color.b
        )
        .unwrap();
        if style.fill {
            write!(
                self.buf,
                r##" fill="#{:02x}{:02x}{:02x}""##,
                style.color.r, style.color.g, style.color.b
            )
            .unwrap();
        } else {
            self.buf.push_str(r#" fill="none""#);
        }
        match style.stroke {
            Stroke::Solid => (),
            Stroke::Dashed => self.buf.push_str(r#" stroke-dasharray="5 3""#),
            Stroke::Dotted => self.buf.push_str(r#" stroke-dasharray="0 3" stroke-linecap="round""#),
        }
    }
}

impl Backend for SVGBackend {
    const BASE_SIZE: f64 = 300.;
    const BASE_SIZE_X: f64 = 300.;
    const BASE_SIZE_Y: f64 = 300.;

    type Output = String;

    fn particle_name(p: &feyngraph_core::model::Particle) -> &str {
        p.name()
    }

    fn init(size_x: f64, size_y: f64) -> Self {
        let mut buf = String::new();
        writeln!(
            buf,
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- Automatically generated by FeynGraph -->
<svg xmlns="http://www.w3.org/2000/svg" width="{:.4}" height="{:.4}" viewBox="0 0 {:.4} {:.4}">
<style> text {{ font-size="{:.4}"; font-family=monospace; }} </style>"#,
            size_x,
            size_y,
            size_x,
            size_y,
            Theme::get_global().font_size * Self::BASE_SIZE,
        )
        .unwrap();
        Self { buf }
    }

    fn finish(mut self) -> Self::Output {
        self.buf.push_str("</svg>");
        self.buf
    }

    fn draw_label(&mut self, label: Label) {
        write!(self.buf, r#"<text x="{:.4}" y="{:.4}""#, label.pos[0], label.pos[1],).unwrap();
        if label.rotate != 0. {
            write!(self.buf, r#" rotate="{:.4}""#, label.rotate).unwrap();
        }
        if !matches!(label.anchor, Anchor::Left) {
            write!(
                self.buf,
                r#" text-anchor="{}""#,
                match label.anchor {
                    Anchor::Left => "start",
                    Anchor::Center => "middle",
                    Anchor::Right => "end",
                }
            )
            .unwrap();
        }
        writeln!(self.buf, ">{}</text>", label.text).unwrap();
    }

    fn draw_segment(&mut self, start: Vec2D, segment: &Segment, style: PathStyle) {
        match segment {
            Segment::Line(x2) => {
                write!(
                    self.buf,
                    r#"<path d="M {:.4} {:.4} L {:.4} {:.4}"#,
                    start[0], start[1], x2[0], x2[1]
                )
                .unwrap();
            }
            Segment::QuadraticBezier(c, x2) => {
                write!(
                    self.buf,
                    r#"<path d="M {:.4} {:.4} Q {:.4} {:.4}, {:.4} {:.4}"#,
                    start[0], start[1], c[0], c[1], x2[0], x2[1]
                )
                .unwrap();
            }
            Segment::CubicBezier(c1, c2, x2) => {
                write!(
                    self.buf,
                    r#"<path d="M {:.4} {:.4} C {:.4} {:.4}, {:.4} {:.4}, {:.4} {:.4}"#,
                    start[0], start[1], c1[0], c1[1], c2[0], c2[1], x2[0], x2[1]
                )
                .unwrap();
            }
        }
        self.style(&style);
        self.buf.push_str("/>\n");
        if let Some(decoration) = style.decoration {
            self.draw_decoration(segment.eval(&start, decoration.pos), decoration);
        }
    }

    fn draw_path(&mut self, start: Vec2D, curve: &Segment, segments: impl Iterator<Item = Segment>, style: PathStyle) {
        write!(self.buf, r#"<path d="M {:.4} {:.4}"#, start[0], start[1]).unwrap();
        for segment in segments {
            match segment {
                Segment::Line(x2) => {
                    write!(self.buf, r#" L {:.4} {:.4}"#, x2[0], x2[1]).unwrap();
                }
                Segment::QuadraticBezier(c, x2) => {
                    write!(self.buf, r#" Q {:.4} {:.4}, {:.4} {:.4}"#, c[0], c[1], x2[0], x2[1]).unwrap();
                }
                Segment::CubicBezier(c1, c2, x2) => {
                    write!(
                        self.buf,
                        r#" C {:.4} {:.4}, {:.4} {:.4}, {:.4} {:.4}"#,
                        c1[0], c1[1], c2[0], c2[1], x2[0], x2[1]
                    )
                    .unwrap();
                }
            }
        }
        self.style(&style);
        self.buf.push_str("/>\n");
        if let Some(decoration) = style.decoration {
            self.draw_decoration(curve.eval(&start, decoration.pos), decoration);
        }
    }

    fn draw_decoration(&mut self, pos: Vec2D, decoration: Decoration) {
        match decoration.kind {
            DecorationKind::Circle => writeln!(
                self.buf,
                r##"<circle cx="{:.4}" cy="{:.4}" r="{:.4}" fill="{}"/>"##,
                pos[0],
                pos[1],
                0.5 * decoration.size * Self::BASE_SIZE,
                Self::fmt_color(&decoration.color)
            )
            .unwrap(),
            DecorationKind::Triangle => {
                let v = Vec2D::from([0.5 * decoration.size * Self::BASE_SIZE, 0.]).rotate(decoration.rotate);
                let v_perp = v.perp();
                writeln!(
                    self.buf,
                    r#"<polygon points="{:.4},{:.4} {:.4},{:.4} {:.4},{:.4}" fill="{}"/>"#,
                    pos[0] + v[0],
                    pos[1] + v[1],
                    pos[0] - v[0] + v_perp[0],
                    pos[1] - v[1] + v_perp[1],
                    pos[0] - v[0] - v_perp[0],
                    pos[1] - v[1] - v_perp[1],
                    Self::fmt_color(&decoration.color)
                )
                .unwrap();
            }
            DecorationKind::Cross => {
                let v = f64::consts::FRAC_1_SQRT_2
                    * decoration.size
                    * Self::BASE_SIZE
                    * Vec2D::from([1., 1.]).rotate(decoration.rotate);
                writeln!(
                    self.buf,
                    r#"<path d="M {:.4},{:.4} L {:.4},{:.4} M {:.4},{:.4} L {:.4},{:.4}"  fill="none" stroke = "{}"/>"#,
                    pos[0] + v[0],
                    pos[1] + v[1],
                    pos[0] - v[0],
                    pos[1] - v[1],
                    pos[0] - v[0],
                    pos[1] + v[1],
                    pos[0] + v[0],
                    pos[1] - v[1],
                    Self::fmt_color(&decoration.color)
                )
                .unwrap();
            }
            DecorationKind::Box => {
                let v = f64::consts::FRAC_1_SQRT_2
                    * decoration.size
                    * Self::BASE_SIZE
                    * Vec2D::from([-0.5, -0.5]).rotate(decoration.rotate);
                writeln!(
                    self.buf,
                    r#"<rect x="{:.4}" y="{:.4}" width="{:.4}" height="{:.4}" fill="{}"/>"#,
                    pos[0] + v[0],
                    pos[1] + v[1],
                    decoration.size * Self::BASE_SIZE,
                    decoration.size * Self::BASE_SIZE,
                    Self::fmt_color(&decoration.color)
                )
                .unwrap();
            }
        }
    }
}
