[package]
name = "feyngraph"
version = "0.0.1"
edition = "2021"

[lib]
name = "feyngraph"
crate-type = ["lib", "cdylib"]

[dependencies]
itertools = "0.14"
rayon = "1"
pest = "2"
pest_derive = "2"
log = "0.4"
thiserror = "2"
indexmap = "2"
pyo3 = { version = "0.23", features = ["auto-initialize"], optional = true}
pyo3-ffi = { version = "0.23", optional = true }
pyo3-log = { version = "0.12", optional = true}

[features]
default = ["python-bindings"]
python-bindings = ["pyo3", "pyo3-log", "pyo3-ffi"]