[package]
name = "feyngraph"
version = "0.0.1"
edition = "2021"

[lib]
name = "feyngraph"
crate-type = ["lib", "cdylib"]

[dependencies]
itertools = "0.14"
rayon = "1"
log = "0.4"
thiserror = "2"
indexmap = "2"
either = "1"
peg = "0.8"
pyo3 = { version = "0.24", features = ["auto-initialize", "either"], optional = true}
pyo3-ffi = { version = "0.24", optional = true }
pyo3-log = { version = "0.12", optional = true}

[dev-dependencies]
paste = "1"
tempfile = "3"
regex = "1"

[features]
default = ["python-bindings"]
python-bindings = ["pyo3", "pyo3-log", "pyo3-ffi"]
