[package]
name = "feyngraph"
version = "0.0.1"
edition = "2021"

[lib]
name = "feyngraph"
crate-type = ["lib", "cdylib"]

[dependencies]
num-traits = "0.2"
itertools = "0.13"
rayon = "1"
pest = "2"
pest_derive = "2"
log = "0.4"
thiserror = "2"
pyo3 = { version = "0.23", features = ["extension-module"], optional = true}
pyo3-log = { version = "0.12", optional = true}

[features]
default = ["python-bindings"]
python-bindings = ["pyo3", "pyo3-log"]