site_name: FeynGraph
site_author: Jens Braun
site_description: "FeynGraph: A modern Feynman diagram generation toolkit"

repo_name: jens-braun/feyngraph
repo_url: https://github.com/Jens-Braun/FeynGraph

copyright: Copyright &copy; 2025 Jens Braun

theme:
    name: material
    features:
        - announce.dismiss
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow

nav:
    - Home: index.md
    - "API Reference": 
        - FeynGraph: feyngraph.md
        - Topology: topology.md

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - toc:
        permalink: true

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [python]
                options:
                    docstring_options:
                        merge_init_into_class: true
                    show_signature_annotations: true
                    signature_crossrefs: true
                    show_source: false
                    summary: true